### ISSUE TITLE
Cool Website

### ISSUE THREAD

**Issue by jeydinpham** [Militia21/MyWebsite#1]
That's a kewl website

**Comment by jeydinpham** [comment]
Can you teach me how the CNAME works?

**Comment by Militia21** [comment]
Uh, the cname is the custom domain. But it's really not necessary.

**Comment by jeydinpham** [comment]
But how you do it .-.

**Comment by ghost** [comment]
Github pages redirect @Jeydin21

**Comment by jeydinpham** [comment]
How does that work o.O

**Comment by jeydinpham** [comment]
All I know how to do is `jeydin21.github.io`

**Comment by ghost** [comment]
So if you  a custom domain then you create a CNAME and put that domain inside the CNAME file

**Comment by jeydinpham** [comment]
So I can just do `jeydin21.com`?

**Comment by ghost** [comment]
If you own the domain then yes!

**Comment by jeydinpham** [comment]
How would I do a `.js.org` domain .-.

**Comment by ghost** [comment]
> How would I do a `.js.org` domain .-.

ah you simply go to the .js.org repo and fork it, then simply edit your changes and stuff. add your github pages domain and make a PR in their repo and you should have ur thing accepted.

**Comment by ghost** [comment]
And if your talking about free domain get it from https://freenom.com or buy your domain at https://domains.google.com

**Comment by ghost** [comment]
btw ur website is pretty kewl

**Comment by jeydinpham** [comment]
Oh, thanks for the info o.O
Which website .-.

**Comment by ghost** [comment]
> Oh, thanks for the info o.O
> Which website .-.

ur main website, github pages. You should get that on jeydin21.js.org

**Comment by jeydinpham** [comment]
o

**Comment by Militia21** [comment]
:O

**Comment by jeydinpham** [comment]
How have you been 👋

**Comment by Militia21** [comment]
Hello! I've been good.

**Comment by jeydinpham** [comment]
Good to hear 🙂
